version: "2"
linters:
  default: none
  enable:
  - godot
  - gosec
  - govet
  - ineffassign
  - staticcheck
  - unparam
  - unused
  - whitespace
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    rules:
    - linters:
      - gosec
      - ineffassign
      path: _test\.go
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - gci
  - gofumpt
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
