run:
  timeout: 5m
linters:
  disable-all: true
  enable:
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
  - gofmt
  - gci
  - godot
  - gofumpt
  - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - ineffassign

    - linters:
        - staticcheck
      text: "SA4006:" #SA4006: this value of `not_used` is never used (staticcheck)
