name: "github"
version: "0.1.1"
usage: "Manage chart repositories on Github"
description: |-
  Provides Github Protocol Support
command: "$HELM_PLUGIN_DIR/bin/helmgithub"
downloaders:
- command: "bin/helmgithub"
  protocols:
  - "github"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
