on:
  push:
    branches:
    - master
  pull_request:
  issue_comment:
    types:
    - created

name: Test
jobs:
  test:
    if: (github.event.issue.pull_request != '' && contains(github.event.comment.body, '/test')) || github.event_name == 'pull_request' || github.event_name == 'push'
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: make test
